### PR TITLE
Adds tests with bats and travis

### PR DESCRIPTION
**Pull request by pcm32**
This PR adds testing and travis support to execute them.

### CODE REVIEW

**Comment by pcm32** [comment]
This is good to go. Test check for exact content loading! Please review when you have a minute @suhaibMo. Travis took a bit of hammering, but working well now.

**Comment by pcm32** [comment]
Found some issues when doing multiple loads... sorting it out now...

**Comment by pcm32** [comment]
Ok @suhaibMo, good to go now with improved testing for multiple datasets and reload of data for the same dataset. Please review when you can to merge, thanks!

**Review by suhaibMo — APPROVED** [review]
Overall the added tests looks good.

**Comment by pcm32** [comment]
Thanks @suhaibMo!

**Pull request merged**
