### PR TITLE
Loading logic, testing and docs for scxa_cell_clusters

### PR DESCRIPTION
**Pull request by pcm32**
This PR adds support for scxa_cell_clusters table loading.

### CODE REVIEW

**Comment by suhaibMo** [comment]
@pcm32 Some travis checks were not successful. Do you still want me to review ?

**Comment by pcm32** [comment]
For some reason travis is stuck...

**Comment by pcm32** [comment]
Hi @suhaibMo I have sorted now the travis issues, so if you want to give it a go, I would really appreciate. Thanks!

**Review by suhaibMo — APPROVED** [review]
Overall seems good, with all tests passing. So for instance if for some k-value the cell_clusters file doesn't exist it will be not be loaded as one file perl k-value.  While loading marker genes if associated k-value is not present loading was skipped.

**Comment by pcm32** [comment]
Thanks @suhaibMo!

**Pull request merged**
