### PR TITLE
Improved container + flyway support

### PR DESCRIPTION
**Pull request by pcm32**
This PR:

- Replaces built-in structural dumps to atlas-scxa flyway setup.
- Changes the container to avoid compilation and incorporate flyway.

This PR shouldn't be merged before the new scanpy one #33 is merged to develop. Superseeds #32.

### CODE REVIEW

**Comment by pcm32** [comment]
ooops... should be fine now.

**Review by pinin4fjords — APPROVED** [review]
A bit of an ITYWFI- but looks good.

**Comment by pcm32** [comment]
> A bit of an ITYWFI

...mmm... I would hope that this wouldn't look so foreign to you at this point...

**Comment by pinin4fjords** [comment]
> > A bit of an ITYWFI
> 
> ...mmm... I would hope that this wouldn't look so foreign to you at this point...

Obviously it's not all strange, but never used Flyway.

**Pull request merged**
